# Generated by Django 4.1 on 2022-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0004_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='update_at_last_news',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
