# Generated by Django 4.1 on 2022-08-15 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0005_category_update_at_last_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_at_last_news',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 16, 43, 41, 906017)),
        ),
    ]
