# Generated by Django 4.1 on 2022-08-20 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0006_alter_category_update_at_last_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_at_last_news',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 23, 10, 56, 279550)),
        ),
        migrations.CreateModel(
            name='ViewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Імя користувача')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yumyum.news', verbose_name='новина')),
            ],
        ),
    ]
