# Generated by Django 4.1 on 2022-08-21 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0008_alter_category_update_at_last_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(db_index=True, max_length=150, verbose_name='Стать')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuserregistration',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='update_at_last_news',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 11, 44, 23, 878289)),
        ),
        migrations.AddField(
            model_name='customuserregistration',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='yumyum.sex', verbose_name='Стать'),
            preserve_default=False,
        ),
    ]
